{
  imports = [
    ./ananicy.nix
    ./appImage.nix
    ./automount.nix
    ./diff.nix
    ./earlyoom.nix
    ./flatpak.nix
    ./fonts.nix
    ./gnome.nix
    ./libvirt.nix
    ./nix-ld.nix
    ./pipewire.nix
    ./plasma.nix
    ./printing.nix
    ./scheduler.nix
    ./secrets.nix
    ./xfce.nix
    ./xserver.nix
  ];
}
