{
  imports = [
    ./alacritty.nix
    ./apps.nix
    ./bash.nix
    ./bat.nix
    ./dircolors.nix
    ./ghostty.nix
    ./direnv.nix
    ./eza.nix
    ./fonts.nix
    ./fzf.nix
    ./gh.nix
    ./home.nix
    ./kitty.nix
    ./neovim.nix
    ./nixgl.nix
    ./openclaw.nix
    ./secrets.nix
    ./spicetify.nix
    ./starship.nix
    ./tmux.nix
    ./wezterm.nix
    ./yt-dlp.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
