matrix: ENC[AES256_GCM,data:T7oSUVK73Dfs6wLhisth/TnlQE0AoGAiyN4+P4ywBhOzSDm5HLH7OhEigIJiUlUKBjN01Bs3tP6KeNw=,iv:U9J2QXSlM07CeaVXdH6kEWPvqIVjh6BlHOs+Af38ulI=,tag:C1KpE/ek/+nHc4kRYM8ylA==,type:str]
sops:
    age:
        - recipient: age1gy4mys83v95r5cdgp2axgv0ma2yk4xhtxesdwjjfljtmxlclh94s896uy8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdzVUeGRkelJtRGNUZWVG
            RUNOcnVSckl6RXRPeFBKOTlBWFJxZEFLb0drClovcjVLSkF0Y1VQaU1hSTNQRlJO
            NFNaTjlBZWowZ3FUelVYUWhKQlNXYW8KLS0tIDMyNlZhMDUzUmY5bHpiSjlZaUQ2
            a1pybEozV2dpN2kzTFJGdElQUENCc2sKKT15eNg4gO4KaRKBILo1V/sLOlarWG6l
            PH19gDdfB/U7ftb+vPRqXl7l0ARBAwukP/VXNOTyJ3f2qaOn3EKAUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T10:41:34Z"
    mac: ENC[AES256_GCM,data:Z3ciH80/H+e3NUItEJfGlzS+xbZxwt5lY31w19Xl6/3K/GxInZFaU2aYlYxUQPRcLREblQbkGyCdml43ZEj1HkDfUQmv0QRkELmnB/R4K4L1oeXhlucyzDjfIEP4va49QHXvZg0BQ+kls1xWrT1KzU5L4wbuhhJOalobssByqCo=,iv:SD0MKT86h8gghvztzLAC+Z2GJWG4uMmphiZTzP4jRLc=,tag:Oc6AbtQpK9uVBBhUS/V7YQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
